### ISSUE TITLE
valueを正しい値に置き換える

### ISSUE THREAD

**Issue by re-taro** [HackU-Kosen-SNCT/webapp#8]
https://github.com/HackU-Kosen-SNCT/webapp/blob/838564556aae9dc1739c232323a1b44da7cca868/src/pages/register/complete.tsx#L15

**Comment by kobapi28** [comment]
item_idをvalueのところに設定してあげればよさそう

**Comment by kobapi28** [comment]
item_idはPOSTリクエストを送信するときに作成されるので値渡ししてあげて、登録してあげる
